#!/usr/bin/env bash

# docker run args
PODMAN_ARGS=""

# build build-env
sudo podman build \
    -t ipxe-build \
    .

# ipxe embedded config provided ?
if [ -f "$1" ]; then
    IPXE_CONF=$(realpath $1)
    echo "embedded ipxe config [$IPXE_CONF]"
    PODMAN_ARGS="--mount type=bind,source=$IPXE_CONF,target=/ipxe.conf,readonly"

    # remove argument from list
    shift
fi

# run make
sudo podman container rm ipxe-env || echo "ok"
sudo podman run \
    --tty \
    --interactive \
    --mount type=bind,source="$(pwd)"/target,target=/mnt/target \
    --name ipxe-env \
    $PODMAN_ARGS \
    ipxe-build \
    $@
